/**
 * OTP Verification Function
 * 
 * Verifies the user-provided OTP against the generated OTP.
 * Valid OTPs for testing: 1234, 5678, 7889, 1209
 * 
 * @param {String} userOTP - OTP provided by the user
 * @param {String} generatedOTP - OTP generated by the triggerOTP workflow
 * @returns {Object} Verification result with status and message
 */
function verifyOTP(userOTP, generatedOTP) {
  // Valid OTPs for testing (from requirements)
  const validOTPs = ["1234", "5678", "7889", "1209"];
  
  // Normalize inputs (remove whitespace, convert to string)
  const normalizedUserOTP = String(userOTP).trim();
  const normalizedGeneratedOTP = String(generatedOTP).trim();
  
  // Check if user OTP is in valid list
  if (!validOTPs.includes(normalizedUserOTP)) {
    return {
      verified: false,
      message: "The OTP you entered is incorrect. Please try again.",
      errorCode: "INVALID_OTP_FORMAT"
    };
  }
  
  // Verify OTP matches
  if (normalizedUserOTP === normalizedGeneratedOTP) {
    return {
      verified: true,
      message: "OTP verified successfully",
      errorCode: null
    };
  } else {
    return {
      verified: false,
      message: "The OTP you entered is incorrect. Please try again.",
      errorCode: "OTP_MISMATCH"
    };
  }
}

// Export for use in Yellow.ai workflow
module.exports = verifyOTP;

// For direct testing
if (typeof window === 'undefined' && require.main === module) {
  // Test cases
  console.log('Test 1 - Valid OTP:', verifyOTP("1234", "1234"));
  console.log('Test 2 - Invalid OTP:', verifyOTP("1234", "5678"));
  console.log('Test 3 - Invalid format:', verifyOTP("9999", "1234"));
  console.log('Test 4 - Valid OTP 2:', verifyOTP("5678", "5678"));
}
